spring:
  application:
    name: fund-mgt

server:
  port: 8080

dubbo:
  protocol:
    name: dubbo
  scan:
    base-packages:
      - com.futao.fund.mgt.service
  registry:
    address: zookeeper://127.0.0.1:2181
