POST {{domain}}/fund/spider-fetch

###
GET {{domain}}/fund/search?sortFields=dailyGrowthRate:desc,nearlyMonth:asc&pageNo=1&pageSize=100

###
GET {{domain}}/fund/search-by-criteria

###
GET {{domain}}/fund/search-by-dsl

###
GET {{domain}}/fund/repository-search?fundCode=004098

###
GET {{domain}}/dubbo-group

###
POST {{domain}}/change-log-level?level=error
